<?php

/**
 * @file
 * Provides Appointment functionality and management for AMT.
 */

use Drupal\amt_appointment\Form\ContinuousAppointmentForm;
use Drupal\Core\Menu\MenuTreeParameters;

/**
 * Implements hook_module_implements_alter().
 *
 * Requests specific hooks to be called after all other modules.
 */
function amt_appointment_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'entity_type_alter'
    || $hook == 'toolbar_alter'
  ) {
    // Moves this module to the end.
    $group = $implementations['amt_appointment'];
    unset($implementations['amt_appointment']);
    $implementations['amt_appointment'] = $group;
  }
}

/**
 * Implements hook_entity_type_alter().
 */
function amt_appointment_entity_type_alter(array &$entityTypes) {
  ContinuousAppointmentForm::alterEntityType($entityTypes);
}

/**
 * Implements hook_toolbar_alter().
 *
 * Patches toolbar module's settings,
 * This is a workaround until the related issue is fixed
 * https://www.drupal.org/node/1869638.
 *
 * @see toolbar_prerender_toolbar_administration_tray()
 */
function amt_appointment_toolbar_alter(&$items) {
  $items['administration']['tray']['toolbar_administration']['#pre_render'] = ['_amt_appointment_toolbar_prerender_admin'];
}

/**
 * Renders the toolbar's administration tray.
 *
 * @param array $element
 *   A renderable array.
 *
 * @return array
 *   The updated renderable array.
 *
 * @see toolbar_prerender_toolbar_administration_tray()
 */
function _amt_appointment_toolbar_prerender_admin(array $element) {
  $menu_tree = \Drupal::service('toolbar.menu_tree');
  $parameters = new MenuTreeParameters();
  $parameters->setRoot('system.admin')
    ->excludeRoot()
    ->setMaxDepth(10)
    ->onlyEnabledLinks();
  $tree = $menu_tree->load(NULL, $parameters);
  $manipulators = [
    ['callable' => 'menu.default_tree_manipulators:checkAccess'],
    ['callable' => 'menu.default_tree_manipulators:generateIndexAndSort'],
    ['callable' => 'toolbar_tools_menu_navigation_links'],
  ];
  $tree = $menu_tree->transform($tree, $manipulators);
  $element['administration_menu'] = $menu_tree->build($tree);
  return $element;
}
