status: 1
pattern: '<?php if (''[events:field_student:entity:field_students]'' == '''') { echo ''[events:field_type], '' . date(''m-d-Y h:i A'', strtotime(''[events:field_date_and_time:value]''));} else { echo ''[events:field_student:entity:field_students], '' . date(''m-d-Y h:i A'', strtotime(''[events:field_date_and_time:value]''));}?>'
php: true
escape: false
dependencies:
  config:
    - eck.eck_type.events.lesson
