module:
  address: 0
  admin_toolbar: 0
  admin_toolbar_tools: 0
  adminimal_admin_toolbar: 0
  amt_appointment: 0
  amt_autocomplete: 0
  amt_charts: 0
  amt_copypaste: 0
  amt_dashboard: 0
  amt_dayview: 0
  amt_feeds: 0
  amt_general: 0
  amt_migrate: 0
  amt_notification: 0
  amt_reports: 0
  amt_royalty: 0
  amt_staff: 0
  amt_studio: 0
  amt_userdashboard: 0
  amt_validations: 0
  auto_entitylabel: 0
  autologout: 0
  automated_cron: 0
  backup_migrate: 0
  better_exposed_filters: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor: 0
  coffee: 0
  color: 0
  color_field: 0
  comment: 0
  conditional_fields: 0
  config: 0
  config_distro: 0
  config_distro_ignore: 0
  config_filter: 0
  config_merge: 0
  config_merge_filter: 0
  config_normalizer: 0
  config_pages: 0
  config_snapshot: 0
  config_sync: 0
  config_update: 0
  config_update_ui: 0
  contact: 0
  contextual: 0
  csv_serialization: 0
  datetime: 0
  dblog: 0
  devel: 0
  disable_field: 0
  draggableviews: 0
  duplicate_role: 0
  dynamic_page_cache: 0
  eck: 0
  editor: 0
  entity: 0
  entity_reference: 0
  entityqueue: 0
  feeds: 0
  feeds_tamper: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  form_mode_control: 0
  form_mode_manager: 0
  front_page: 0
  help: 0
  history: 0
  image: 0
  inline_entity_form: 0
  link: 0
  link_to_entity: 0
  mailsystem: 0
  menu_export: 0
  menu_per_role: 0
  menu_ui: 0
  migrate: 0
  migrate_drupal: 0
  migrate_drupal_ui: 0
  migrate_plus: 0
  migrate_tools: 0
  node: 0
  office_hours: 0
  options: 0
  page_cache: 0
  path: 0
  quickedit: 0
  rdf: 0
  redirect_after_login: 0
  rest: 0
  search: 0
  serialization: 0
  shortcut: 0
  smtp: 0
  structure_sync: 0
  superfish: 0
  swiftmailer: 0
  system: 0
  tamper: 0
  taxonomy: 0
  telephone: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  twig_tweak: 0
  twilio: 0
  ultimate_cron: 0
  update: 0
  user: 0
  views_autocomplete_filters: 0
  views_conditional: 0
  views_data_export: 0
  views_ui: 0
  menu_link_content: 1
  views: 10
  config_provider: 100
  standard: 1000
theme:
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
  bootstrap: 0
  amt: 0
  adminimal_theme: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
