name: Config Distro Ignore
type: module
description: Retain custom configuration when importing the distribution configuration.
# core: 8.x
package: Config
dependencies:
  - config_distro:config_distro

# Information added by Drupal.org packaging script on 2018-10-09
version: '8.x-1.0-alpha3'
core: '8.x'
project: 'config_distro'
datestamp: 1539071283
