# Schema for the configuration files of the Menu per Role module.

menu_per_role.settings:
  type: config_object
  label: 'Menu per role settings'
  mapping:
    uid1_see_all:
      type: boolean
      label: 'Allow the UID 1 to see all the links and options.'
    admin_see_all:
      type: boolean
      label: 'Allow administrators to see all the links and options.'
    hide_show:
      type: integer
      label: 'Select what is shown when editing menu items.'
    hide_on_content:
      type: integer
      label: 'Show fields on menu items that point to content.'
